on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

permissions:
  contents: read


jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - run: |
        docker build -t godot-web .
